### ISSUE TITLE
Remember the card number, number prefix and co-author from the acp command

### ISSUE THREAD

**Issue by richardjohnsonfarukh** [richardjohnsonfarukh/git-util#19]
Save the metadata for the commit message in a yaml inside the repo as:

```yaml
'repo-name': 
  'co-author': Some Author
  'issue': 'something#123'
```
